In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.0'

In [3]:
dataset = pd.read_csv(r'C:\Users\meetd\OneDrive\Desktop\Datasets\bank\Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [7]:
print(x[:,:])

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x.shape)

(10000, 12)


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [12]:
ann = tf.keras.models.Sequential()

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [14]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy'])

In [15]:
ann.fit(x_train, y_train, batch_size=32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 908us/step - loss: 0.5773 - accuracy: 0.7565
Epoch 2/100
250/250 [==============================] - 0s 731us/step - loss: 0.4728 - accuracy: 0.7995
Epoch 3/100
250/250 [==============================] - 0s 728us/step - loss: 0.4524 - accuracy: 0.7933
Epoch 4/100
250/250 [==============================] - 0s 767us/step - loss: 0.4151 - accuracy: 0.8124
Epoch 5/100
250/250 [==============================] - 0s 697us/step - loss: 0.3994 - accuracy: 0.8293
Epoch 6/100
250/250 [==============================] - 0s 703us/step - loss: 0.3737 - accuracy: 0.8416
Epoch 7/100
250/250 [==============================] - 0s 682us/step - loss: 0.3646 - accuracy: 0.8489
Epoch 8/100
250/250 [==============================] - 0s 811us/step - loss: 0.3671 - accuracy: 0.8452
Epoch 9/100
250/250 [==============================] - 0s 807us/step - loss: 0.3438 - accuracy: 0.8570
Epoch 10/100
250/250 [==============================] - 0s 691us/step - l

250/250 [==============================] - 0s 659us/step - loss: 0.3238 - accuracy: 0.8675
Epoch 80/100
250/250 [==============================] - 0s 663us/step - loss: 0.3241 - accuracy: 0.8611
Epoch 81/100
250/250 [==============================] - 0s 663us/step - loss: 0.3258 - accuracy: 0.8677
Epoch 82/100
250/250 [==============================] - 0s 697us/step - loss: 0.3377 - accuracy: 0.8608
Epoch 83/100
250/250 [==============================] - 0s 635us/step - loss: 0.3225 - accuracy: 0.8677
Epoch 84/100
250/250 [==============================] - 0s 654us/step - loss: 0.3246 - accuracy: 0.8714
Epoch 85/100
250/250 [==============================] - 0s 751us/step - loss: 0.3130 - accuracy: 0.8716
Epoch 86/100
250/250 [==============================] - 0s 695us/step - loss: 0.3321 - accuracy: 0.8628
Epoch 87/100
250/250 [==============================] - 0s 791us/step - loss: 0.3244 - accuracy: 0.8651
Epoch 88/100
250/250 [==============================] - 0s 657us/step - loss:

In [16]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [17]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1529   66]
 [ 203  202]]


0.8655